# Welcome to Jekyll!
#
# This config file contains settings that affect your entire site.
# If you change this file, please restart the server process
# (e.g., `bundle exec jekyll serve`).

# -----------------------------------------------------------------------------
# SITE SETTINGS
# -----------------------------------------------------------------------------
title: Spo0ky
email: spo0kydevops@gmail.com
description: "Trust No 1"
url: "https://spo0ky.dev" # Your custom domain
baseurl: ""               # Root (no subpath), e.g. spo0ky.dev/
twitter_username: spo0kydev
github_username:  Spo0kyDev

# -----------------------------------------------------------------------------
# BUILD SETTINGS
# -----------------------------------------------------------------------------
markdown: kramdown
theme:
plugins:
  - jekyll-feed

# -----------------------------------------------------------------------------
# CUSTOM VARIABLES
# -----------------------------------------------------------------------------
mystique: "The truth is elusive, but the code speaks volumes."
curiosity: "Through curiosity, we find clarity. Through code, we find creation."
digital_realm: "Beyond the surface, there's a world waiting to be discovered."

# Additional customization (example color palette)
color_palette:
  background: "#000000"  # Matrix-inspired black
  text:       "#00ff00"  # Neon green
  accent:     "#00ccff"  # Subtle cyan for contrast

# -----------------------------------------------------------------------------
# EXCLUSIONS
# -----------------------------------------------------------------------------
# These paths/files will not be processed by Jekyll.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
