# Basic Info
title: Spo0ky Portfolio
description: website for protfolio
url: url: https://spo0ky.dev
remote_theme: pages-themes/hacker@v0.2.0

# Plugins
plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-seo-tag

# Header Pages
header_pages:
  - index.md
  - about.md

# Styling and Fonts
sass:
  style: compressed

# Markdown and Syntax Highlighting
markdown: kramdown
highlighter: rouge

# Optional Additions
github_username: Spo0kyDev

# Pagination (if using blog posts)
paginate: 5
paginate_path: "/blog/page:num"

# Custom Favicon and Logo
logo: /assets/images/logo.png
favicon: /assets/images/favicon.ico

# Site Theme Color (for mobile browsers)
theme_color: "#00ff00"
